DROP TABLE IF EXISTS `CUSTOMER`;

CREATE TABLE `CUSTOMER` (
  `ID` varchar(45) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `TELEPHONE` varchar(100) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `ADDRESS` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE `PRODUCT` (
  `ID` varchar(45) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `PRICE` decimal  NOT NULL,
  `EXPIRED_DATE` date  DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;